language: generic
services:
  - docker

env:
  matrix:
    - ROS_DISTRO="crystal"
    - ROS_DISTRO="dashing"

install:
  -  git clone --quiet --depth 1 https://github.com/ipa-mdl/industrial_ci.git .industrial_ci -b colcon-rebase  # Use a fork because original does not support ROS2 for now
script:
  - .industrial_ci/travis.sh
