language: generic
services:
  - docker

env:
  matrix:
    - ROS_DISTRO="crystal"
    - ROS_DISTRO="dashing"

install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci
script:
  - .industrial_ci/travis.sh
