name: Test Sources

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
    branches-ignore:
      - 'released'
  schedule:
    - cron:  '0 22 * * *'

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

  test-sources:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        python: [3.10]
        include:
          - os: ubuntu-20.04
            DEPENDENCIES_INSTALLATION: "sudo apt -y install clang-format-10 cppcheck"
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      if: github.event_name == 'schedule' || github.event.pull_request.draft == false || contains(github.event.pull_request.labels.*.name, 'test sources')
      with:
        submodules: true
    - name: Set up Python 3.10
      if: github.event_name == 'schedule' || github.event.pull_request.draft == false || contains(github.event.pull_request.labels.*.name, 'test sources')
      uses: actions/setup-python@v4
      with:
        python-version: 3.10
    - name: Test Sources
      if: github.event_name == 'schedule' || github.event.pull_request.draft == false || contains(github.event.pull_request.labels.*.name, 'test sources')
      run: |
        ${{ matrix.DEPENDENCIES_INSTALLATION }}
        pip install -r tests/sources/requirements.txt
        python3 -m unittest discover -s tests/sources/