name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  industrial_ci:
    strategy:
      fail-fast: false
      matrix:
        ROS_REPO: [main, testing]
        ROS_DISTRO: [foxy, rolling]
    runs-on: ubuntu-latest
    env:
      AFTER_INIT: ./scripts/ci_after_init.bash ${ROS_DISTRO} ${ROS_REPO}
      BEFORE_INIT_EMBED: source scripts/ci_before_init_embed.bash
    steps:
      - uses: actions/checkout@v1
        with:
         submodules: recursive
      - uses: 'ros-industrial/industrial_ci@master'
        continue-on-error: true
        env: 
          ROS_REPO: ${{matrix.ROS_REPO}}
          ROS_DISTRO: ${{matrix.ROS_DISTRO}}
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: artifacts
          retention-days: 5
